openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: https://localhost:3000
    description: Local server
  - url: https://task-api-4h6j.onrender.com
    description: Production server
tags:
  - name: Tasks
    description: Operations related to tasks
paths:
  /tasks:
    get:
      summary: Get all tasks
      tags:
        - Tasks
      parameters:
        - name: completed
          in: query
          required: false
          description: Filter tasks by completed status
          schema:
            type: boolean
            example: true
        - name: limit
          in: query
          required: false
          description: Max number of tasks to return
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
    post:
      summary: Create a new task
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
  /tasks/{id}:
    get:
      summary: Get a task by ID
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
components:
  schemas:
    Task:
      Task:
        type: object
        properties:
          id:
            type: integer
            example: 1
          title:
            type: string
            example: Buy groceries
          completed:
            type: boolean
            example: false
    ValidationError:
      ValidationError:
        type: object
        properties:
          error:
            type: string
            example: Validation failed
          details:
            type: array
            items:
              type: string
            example:
              - Title is required
    NotFoundError:
      type: object
      properties:
        error:
          type: string
          example: Task not found
      required:
        - error
