openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: https://localhost:3000
tags:
  - name: Tasks
    description: Operations related to tasks

paths:
  $ref: './paths/tasks.yaml'

